### ISSUE TITLE
Support for `smtp` vs `smtps` 

### ISSUE THREAD

**Issue by SanjulaGanepola** [ThePrez/Manzan#129]
After the change made in https://github.com/ThePrez/Manzan/pull/126 to go from `smtp` to `smtps`, I noticed that we can no longer use a server such as `na.relay.ibm.com`. This is because of the port that it ends up using:
- `smtp`  -> 25
- `smtps` -> 465

Option 1: Support both `smtp` and `smtp` as a destination `<id>`.
Option 2: Support only `smtp` as the `<id>` and add an optional field for the port where the default is 25.

@ThePrez @jonnyz32 What are your thoughts on this?

I think option 2 is probably better since users can set whatever SMTP port they want based on what they have configured as it looks like there are even a few more typical SMTP ports:
![image](https://github.com/user-attachments/assets/56cb2ebf-0bda-42f3-b2ac-c2ad5ffdfb0a)

**Comment by ThePrez** [comment]
Thanks for catching, Sanjula! 

I think we need to do Option 1, simply because it's hypothetically possible to host smtp on 465 and smtps on 25, etc. 
From a code perspective, it's a matter of just duplicating the logic for smtp and smtps and allowing for port configuration (I think that's already done)
